// <auto-generated />
using System;
using Eventify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eventify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207160952_Seed-Data")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eventify.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("ArabicAddress")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ArabicFullName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("BIO")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("BackIdPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FrontIdPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalIDNumber")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("EventVerification")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("BIT");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INT");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Address = "Cairo Grand Hall, Nasr City",
                            Capacity = 700,
                            Category = 1,
                            Description = "A conference discussing the future of AI and technology.",
                            EndDateTime = new DateTime(2025, 12, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Tech Innovations Conference 2025",
                            EventVerification = 2,
                            Features = "Speakers, Workshops, Networking",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 12, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TicketPrice = 500m,
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            Address = "Dubai Outdoor Arena, Marina Walk",
                            Capacity = 700,
                            Category = 8,
                            Description = "Intense fitness session with professional trainers.",
                            EndDateTime = new DateTime(2025, 5, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Outdoor Fitness Bootcamp",
                            EventVerification = 1,
                            Features = "Trainers, Fresh Air, Group Activities",
                            IsPrivate = false,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 5, 3, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TicketPrice = 150m,
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 3,
                            Address = "Riyadh Event Center",
                            Capacity = 700,
                            Category = 5,
                            Description = "Connect with entrepreneurs and business owners.",
                            EndDateTime = new DateTime(2025, 6, 18, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Riyadh Business Networking Night",
                            EventVerification = 2,
                            Features = "Networking, Snacks, Business Talks",
                            IsPrivate = false,
                            OrganizerId = 6,
                            StartDateTime = new DateTime(2025, 6, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TicketPrice = 300m,
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 4,
                            Address = "Corniche Road",
                            Capacity = 700,
                            Category = 10,
                            Description = "Live music performances by local bands.",
                            EndDateTime = new DateTime(2025, 7, 10, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Alexandria Summer Music Festival",
                            EventVerification = 2,
                            Features = "Live Bands, Food Trucks, Sea View",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 7, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 200m,
                            VenueId = 4
                        },
                        new
                        {
                            EventId = 5,
                            Address = "Pyramids Road",
                            Capacity = 700,
                            Category = 3,
                            Description = "A meetup focusing on ancient Egyptian culture.",
                            EndDateTime = new DateTime(2025, 3, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Giza Cultural Meetup",
                            EventVerification = 2,
                            Features = "Guided Tour, Cultural Talks",
                            IsPrivate = true,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TicketPrice = 250m,
                            VenueId = 5
                        },
                        new
                        {
                            EventId = 6,
                            Address = "Khalifa Street",
                            Capacity = 700,
                            Category = 6,
                            Description = "A premium exhibition showcasing luxury brands.",
                            EndDateTime = new DateTime(2025, 9, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Abu Dhabi Luxury Expo",
                            EventVerification = 2,
                            Features = "Exhibitions, VIP Lounge",
                            IsPrivate = false,
                            OrganizerId = 6,
                            StartDateTime = new DateTime(2025, 9, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 800m,
                            VenueId = 6
                        },
                        new
                        {
                            EventId = 7,
                            Address = "Jeddah North Corniche",
                            Capacity = 700,
                            Category = 9,
                            Description = "A charity sports event to support children’s hospitals.",
                            EndDateTime = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Jeddah Beach Charity Run",
                            EventVerification = 2,
                            Features = "Medals, Refreshments",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 2, 20, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 100m,
                            VenueId = 7
                        },
                        new
                        {
                            EventId = 8,
                            Address = "Doha Convention Hall",
                            Capacity = 700,
                            Category = 2,
                            Description = "Hands-on workshop for beginners in software development.",
                            EndDateTime = new DateTime(2025, 8, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Doha Tech Workshop",
                            EventVerification = 2,
                            Features = "Coding Session, Mentors",
                            IsPrivate = false,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 350m,
                            VenueId = 8
                        },
                        new
                        {
                            EventId = 9,
                            Address = "Luxor Temple Road",
                            Capacity = 700,
                            Category = 4,
                            Description = "A seminar discussing ancient Egyptian heritage.",
                            EndDateTime = new DateTime(2025, 11, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Luxor Historical Seminar",
                            EventVerification = 3,
                            Features = "Speakers, Guided Discussion",
                            IsPrivate = false,
                            OrganizerId = 6,
                            StartDateTime = new DateTime(2025, 11, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TicketPrice = 180m,
                            VenueId = 9
                        },
                        new
                        {
                            EventId = 10,
                            Address = "Sharjah Art Gallery",
                            Capacity = 700,
                            Category = 10,
                            Description = "A digital art exhibition featuring creatives from the region.",
                            EndDateTime = new DateTime(2025, 10, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Sharjah Digital Art Expo",
                            EventVerification = 2,
                            Features = "Digital Art Panels, Artist Meetups",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 10, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 220m,
                            VenueId = 10
                        },
                        new
                        {
                            EventId = 11,
                            Address = "Pyramids Road",
                            Capacity = 700,
                            Category = 3,
                            Description = "A meetup focusing on ancient Egyptian culture.",
                            EndDateTime = new DateTime(2025, 3, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Giza Cultural Meetup",
                            EventVerification = 2,
                            Features = "Guided Tour, Cultural Talks",
                            IsPrivate = false,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 3, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TicketPrice = 250m,
                            VenueId = 5
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.EventPhoto", b =>
                {
                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("EventId")
                        .HasColumnType("INT");

                    b.HasKey("PhotoUrl", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventPhotos", (string)null);

                    b.HasData(
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_1.jpg",
                            EventId = 11
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_2.jpg",
                            EventId = 11
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_3.jpg",
                            EventId = 11
                        },
                        new
                        {
                            PhotoUrl = "/images/event1_4.jpg",
                            EventId = 11
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<int?>("EventId")
                        .HasColumnType("INT");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasFilter("[EventId] IS NOT NULL");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Amount = 200m,
                            EventId = 4,
                            EventName = "Alexandria Summer Music Festival",
                            PaymentDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT4-001",
                            status = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 800m,
                            EventId = 6,
                            EventName = "Abu Dhabi Luxury Expo",
                            PaymentDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT6-001",
                            status = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100m,
                            EventId = 7,
                            EventName = "Jeddah Beach Charity Run",
                            PaymentDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT7-001",
                            status = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 350m,
                            EventId = 8,
                            EventName = "Doha Tech Workshop",
                            PaymentDate = new DateTime(2025, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT8-001",
                            status = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 220m,
                            EventId = 10,
                            EventName = "Sharjah Digital Art Expo",
                            PaymentDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT10-001",
                            status = 2
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("AirConditioningAvailable")
                        .HasColumnType("BIT");

                    b.Property<bool>("AudioVisualEquipment")
                        .HasColumnType("BIT");

                    b.Property<bool>("BarServiceAvailable")
                        .HasColumnType("BIT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INT");

                    b.Property<bool>("CateringAvailable")
                        .HasColumnType("BIT");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(Max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INT");

                    b.Property<bool>("ParkingAvailable")
                        .HasColumnType("BIT");

                    b.Property<int>("PricePerHour")
                        .HasColumnType("INT");

                    b.Property<string>("ProofOfOwnership")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("RestroomsAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("SpecialFeatures")
                        .HasColumnType("VARCHAR(Max)");

                    b.Property<int>("VenueType")
                        .HasColumnType("int");

                    b.Property<int?>("VenueVerification")
                        .HasColumnType("int");

                    b.Property<bool>("WifiAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Venues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nasr City",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = false,
                            Capacity = 500,
                            CateringAvailable = true,
                            Country = 1,
                            Description = "Large premium indoor venue.",
                            Name = "Cairo Grand Hall",
                            OwnerId = 1,
                            ParkingAvailable = true,
                            PricePerHour = 2500,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Stage, LED Screens",
                            VenueType = 1,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "11371"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Marina Walk",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = true,
                            Capacity = 300,
                            CateringAvailable = true,
                            Country = 3,
                            Description = "Open-air event arena with sea view.",
                            Name = "Dubai Outdoor Arena",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 1800,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Sea View",
                            VenueType = 2,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "00000"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Olaya Street",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = false,
                            Capacity = 700,
                            CateringAvailable = false,
                            Country = 2,
                            Description = "Modern multi-purpose venue.",
                            Name = "Riyadh Event Center",
                            OwnerId = 3,
                            ParkingAvailable = true,
                            PricePerHour = 3000,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "VIP Rooms",
                            VenueType = 1,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "11564"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Corniche Road",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 250,
                            CateringAvailable = true,
                            Country = 1,
                            Description = "Outdoor venue with stunning sea view.",
                            Name = "Alexandria Seaside Hall",
                            OwnerId = 1,
                            ParkingAvailable = false,
                            PricePerHour = 1500,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Sea Breeze, Open Stage",
                            VenueType = 2,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "21500"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Pyramids Road",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 600,
                            CateringAvailable = true,
                            Country = 1,
                            Description = "Cultural event venue facing pyramids.",
                            Name = "Giza Pyramid Arena",
                            OwnerId = 1,
                            ParkingAvailable = true,
                            PricePerHour = 3500,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Historic View",
                            VenueType = 2,
                            VenueVerification = 2,
                            WifiAvailable = false,
                            ZIP = "12556"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Khalifa Street",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = true,
                            Capacity = 450,
                            CateringAvailable = true,
                            Country = 3,
                            Description = "Luxury indoor venue for premium events.",
                            Name = "Abu Dhabi Royal Hall",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 4000,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Gold Interior, VIP Lounge",
                            VenueType = 1,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "00001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "North Corniche",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = true,
                            Capacity = 800,
                            CateringAvailable = false,
                            Country = 2,
                            Description = "Outdoor beach concert venue.",
                            Name = "Jeddah Beach Stage",
                            OwnerId = 3,
                            ParkingAvailable = true,
                            PricePerHour = 2800,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Beachfront Stage",
                            VenueType = 2,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "23415"
                        },
                        new
                        {
                            Id = 8,
                            Address = "West Bay",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = false,
                            Capacity = 1000,
                            CateringAvailable = false,
                            Country = 6,
                            Description = "Large conference and exhibition hall.",
                            Name = "Doha Convention Hall",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 5000,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Conference Rooms",
                            VenueType = 1,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "00022"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Luxor Temple Road",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 350,
                            CateringAvailable = false,
                            Country = 1,
                            Description = "Historic indoor cultural venue.",
                            Name = "Luxor Cultural Theatre",
                            OwnerId = 1,
                            ParkingAvailable = true,
                            PricePerHour = 1700,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Theatre Stage",
                            VenueType = 1,
                            VenueVerification = 2,
                            WifiAvailable = false,
                            ZIP = "85958"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Art District",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 120,
                            CateringAvailable = false,
                            Country = 3,
                            Description = "Gallery space for exhibitions.",
                            Name = "Sharjah Art Gallery",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 900,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Art Lighting",
                            VenueType = 1,
                            VenueVerification = 2,
                            WifiAvailable = true,
                            ZIP = "00033"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Luxor Temple Road",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 350,
                            CateringAvailable = false,
                            Country = 1,
                            Description = "Historic indoor cultural venue.",
                            Name = "Luxor Cultural Theatre",
                            OwnerId = 1,
                            ParkingAvailable = true,
                            PricePerHour = 1700,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Theatre Stage",
                            VenueType = 1,
                            VenueVerification = 1,
                            WifiAvailable = false,
                            ZIP = "85958"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Art District",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 120,
                            CateringAvailable = false,
                            Country = 3,
                            Description = "Gallery space for exhibitions.",
                            Name = "Sharjah Art Gallery",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 900,
                            ProofOfOwnership = "/Images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Art Lighting",
                            VenueType = 1,
                            VenueVerification = 3,
                            WifiAvailable = true,
                            ZIP = "00033"
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.VenuePhoto", b =>
                {
                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("VenueId")
                        .HasColumnType("INT");

                    b.HasKey("PhotoUrl", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenuePhotos", (string)null);

                    b.HasData(
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_1.jpg",
                            VenueId = 10
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_2.jpg",
                            VenueId = 10
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_3.jpg",
                            VenueId = 10
                        },
                        new
                        {
                            PhotoUrl = "/images/venue1_4.jpg",
                            VenueId = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eventify.Models.Entities.Admin", b =>
                {
                    b.HasBaseType("Eventify.Models.Entities.ApplicationUser");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ConcurrencyStamp = "56c4c15e-5b0e-4e32-9251-129e66f1bc3c",
                            Email = "Admin1@test.com",
                            EmailConfirmed = true,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@TEST.COM",
                            NormalizedUserName = "MOHAMED",
                            PasswordHash = "AQAAAAIAAYagAAAAEOcM+WV5PYPz1Nc/GYORv4izIrGTm2EpIKBcSb39FExUBEW7HY8j27zsWgf98HQQGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Mohamed"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ConcurrencyStamp = "f6ac9b2b-ad53-4c23-8c41-fde9c608af73",
                            Email = "Admin2@test.com",
                            EmailConfirmed = true,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@TEST.COM",
                            NormalizedUserName = "AABAS",
                            PasswordHash = "AQAAAAIAAYagAAAAENcbwSPhEqReuhTfLG3D4mEefSzVzCNzHIewxxnsdHt7zQz45Jj7XeZ9Dhxf8SB6Rw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Aabas"
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Organizer", b =>
                {
                    b.HasBaseType("Eventify.Models.Entities.ApplicationUser");

                    b.Property<int>("ExperienceYear")
                        .HasMaxLength(50)
                        .HasColumnType("INT");

                    b.Property<int>("PastEventCount")
                        .HasMaxLength(50)
                        .HasColumnType("INT");

                    b.Property<string>("Specialization")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasDiscriminator().HasValue("Organizier");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "69cf7d1c-f55a-4064-a3cb-d6f0ea29d8a6",
                            Country = 1,
                            Email = "Organizer1@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER1@TEST.COM",
                            NormalizedUserName = "FARES",
                            PasswordHash = "AQAAAAIAAYagAAAAEPon+LAeaVcU9y522j68PYf95MdMXgTtG/IA1WLCb9dIU5wSztUn0FEIWOBf+cmNSQ==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Fares",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "94aba313-f5e0-4376-9095-a1e248fb05cf",
                            Country = 1,
                            Email = "Organizer2@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER2@TEST.COM",
                            NormalizedUserName = "AHMED",
                            PasswordHash = "AQAAAAIAAYagAAAAEOrglHzOM6D6XknSB/Lgto2+ghiKVOQDjklQ3i379f9zKP8Y9GQB+m+36O/2Cy5l+A==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Ahmed",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "bcc42951-01f3-470d-b63e-9e66690d5ee5",
                            Country = 1,
                            Email = "Organizer3@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER3@TEST.COM",
                            NormalizedUserName = "ZIAD",
                            PasswordHash = "AQAAAAIAAYagAAAAEGbp6Qf3oXsCAr4hCuOYFIQ3XMVGmUlNCjM6aZiKv9mo6trD3sTKS6Td7vKilSdFyA==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Ziad",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            AccountStatus = 3,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "b4cd4cfb-6bd0-4fc1-94eb-e226a2c54d39",
                            Country = 10,
                            Email = "Organizer4@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER4@TEST.COM",
                            NormalizedUserName = "ASHRAF",
                            PasswordHash = "AQAAAAIAAYagAAAAENsOnte0LWHy/wRQ9djHCX2YrEpCh9OEENkNtyLOp2WYKXU7WFAy1kqC5sYrKOckcA==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Ashraf",
                            ExperienceYear = 5,
                            PastEventCount = 0,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            AccountStatus = 1,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "9e330517-6811-4d62-a5db-98811ed45c19",
                            Country = 3,
                            Email = "Organizer5@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER5@TEST.COM",
                            NormalizedUserName = "ZAATR",
                            PasswordHash = "AQAAAAIAAYagAAAAEMP90NI0G47txWudcFAGtScMNm29XBSrOGibXWSb8Pjmu+SItDZTLlY4SCJevodqbw==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Zaatr",
                            ExperienceYear = 5,
                            PastEventCount = 0,
                            Specialization = "Tech Events"
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Owner", b =>
                {
                    b.HasBaseType("Eventify.Models.Entities.ApplicationUser");

                    b.Property<int>("VenueCount")
                        .HasColumnType("INT");

                    b.Property<decimal>("WithdrawableEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.HasDiscriminator().HasValue("Owner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "fb2a7e1f-6c2f-4551-ad87-eebd86125ee7",
                            Country = 1,
                            Email = "Owner1@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER1@TEST.COM",
                            NormalizedUserName = "MAHMOUD",
                            PasswordHash = "AQAAAAIAAYagAAAAELhV8UB0VPOAa8dERvibx6cXfM4K+a3rcOPGgbJYTGXztSc73UHhjyfbdlDri24x7Q==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Mahmoud",
                            VenueCount = 3,
                            WithdrawableEarnings = 15000.75m
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "3b0d03ed-55d9-464a-a381-7f8e41833303",
                            Country = 1,
                            Email = "Owner2@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER2@TEST.COM",
                            NormalizedUserName = "ALI",
                            PasswordHash = "AQAAAAIAAYagAAAAEJcLenrGrSGxlXGEw2kJtIs5cIBL1expYxlA7WaIiaaQEQfKfRt0nu/mJZFnngSL+Q==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Ali",
                            VenueCount = 3,
                            WithdrawableEarnings = 15000.75m
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            AccountStatus = 2,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "22831e51-a615-439b-abb3-9cc15816fa01",
                            Country = 1,
                            Email = "Owner3@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER3@TEST.COM",
                            NormalizedUserName = "AMR",
                            PasswordHash = "AQAAAAIAAYagAAAAECyq28j8Kf/8Y3k9GwadN8DwYUN5lGemqHI0CyAc5D+4Uz9WTCJQetXuxyhaOlFNwQ==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Amr",
                            VenueCount = 3,
                            WithdrawableEarnings = 15000.75m
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            AccountStatus = 1,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "4b7dbb0f-b62a-4af1-ad6e-108cbb7f79f0",
                            Country = 1,
                            Email = "Owner4@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER4@TEST.COM",
                            NormalizedUserName = "RAMI",
                            PasswordHash = "AQAAAAIAAYagAAAAEKaLn4V2SOVS47ChoxCj++pfUej5upulTjOGgf9b9mloHeas2krKzDWmtRFn20q7fQ==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Rami",
                            VenueCount = 0,
                            WithdrawableEarnings = 15000.75m
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            AccountStatus = 3,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "/Images/back1.jpg",
                            ConcurrencyStamp = "05a92b34-4eeb-48f8-b0ef-3893e5b6c906",
                            Country = 2,
                            Email = "Owner5@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "/Images/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER5@TEST.COM",
                            NormalizedUserName = "ANAS",
                            PasswordHash = "AQAAAAIAAYagAAAAEEqYcioqnwMD54vpwhj0K7LH1YvrrC8wcqyTP6v01drNTpd6pedmnjvTp30mpO76Cg==",
                            PhoneNumberConfirmed = false,
                            Photo = "/Images/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Anas",
                            VenueCount = 0,
                            WithdrawableEarnings = 15000.75m
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventify.Models.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Eventify.Models.Entities.EventPhoto", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Event", "Event")
                        .WithMany("EventPhotos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Payment", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Event", "Event")
                        .WithOne("Payment")
                        .HasForeignKey("Eventify.Models.Entities.Payment", "EventId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Owner", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Eventify.Models.Entities.VenuePhoto", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Venue", "Venue")
                        .WithMany("VenuePhotos")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.Navigation("EventPhotos");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("VenuePhotos");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Owner", b =>
                {
                    b.Navigation("Venues");
                });
#pragma warning restore 612, 618
        }
    }
}
