// <auto-generated />
using System;
using Eventify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eventify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128194350_Organizer")]
    partial class Organizer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eventify.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ArabicAddress")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ArabicFullName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("BIO")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("BackIdPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FrontIdPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalIDNumber")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Features")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("BIT");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INT");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Eventify.Models.Entities.EventPhoto", b =>
                {
                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("EventId")
                        .HasColumnType("INT");

                    b.HasKey("PhotoUrl", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventPhotos", (string)null);
                });

            modelBuilder.Entity("Eventify.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<int?>("EventId")
                        .HasColumnType("INT");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasFilter("[EventId] IS NOT NULL");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("AirConditioningAvailable")
                        .HasColumnType("BIT");

                    b.Property<bool>("AudioVisualEquipment")
                        .HasColumnType("BIT");

                    b.Property<bool>("BarServiceAvailable")
                        .HasColumnType("BIT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INT");

                    b.Property<bool>("CateringAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(Max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INT");

                    b.Property<bool>("ParkingAvailable")
                        .HasColumnType("BIT");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("ProofOfOwnership")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("RestroomsAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("SpecialFeatures")
                        .IsRequired()
                        .HasColumnType("VARCHAR(Max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("VenueType")
                        .HasColumnType("int");

                    b.Property<bool>("WifiAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("Eventify.Models.Entities.VenuePhoto", b =>
                {
                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("VenueId")
                        .HasColumnType("INT");

                    b.HasKey("PhotoUrl", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenuePhotos", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eventify.Models.Entities.Organizer", b =>
                {
                    b.HasBaseType("Eventify.Models.Entities.ApplicationUser");

                    b.Property<int>("ExperienceYear")
                        .HasMaxLength(50)
                        .HasColumnType("INT");

                    b.Property<int>("PastEventCount")
                        .HasMaxLength(50)
                        .HasColumnType("INT");

                    b.Property<string>("Specialization")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasDiscriminator().HasValue("Organizier");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "d2ef2bc3-feb9-43df-a798-569418a51634",
                            Country = 1,
                            Email = "Organizer1@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER1@TEST.COM",
                            NormalizedUserName = "FARES",
                            PasswordHash = "AQAAAAIAAYagAAAAEJBpTyyvJ0sHYPQ+NgQe5y3n2a1Zgxk2c9RuyHo7aUZPuBfVUY41k2K5HkTtbcX6Rw==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            TwoFactorEnabled = false,
                            UserName = "Fares",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "4787fa46-b873-4598-95e4-dc973b3cf768",
                            Country = 1,
                            Email = "Organizer2@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER2@TEST.COM",
                            NormalizedUserName = "AHMED",
                            PasswordHash = "AQAAAAIAAYagAAAAEH5RBCYP6r/JwuUGaSrt+i/xwcA3AQ8UDxRhq4HYBIN1vRIjguQK6pVVZ9Ge6xGdDQ==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            TwoFactorEnabled = false,
                            UserName = "Ahmed",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "f7a3df34-c2d3-49e9-9bd1-9b0846af6349",
                            Country = 1,
                            Email = "Organizer3@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER3@TEST.COM",
                            NormalizedUserName = "ZIAD",
                            PasswordHash = "AQAAAAIAAYagAAAAEOQsgVdVfIpBwUuFRGflz4CfyxTIDJFC9wDziNk5DPFnKwCXH1d0M0mU7WLS0VPlSw==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            TwoFactorEnabled = false,
                            UserName = "Ziad",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Owner", b =>
                {
                    b.HasBaseType("Eventify.Models.Entities.ApplicationUser");

                    b.Property<int>("VenueCount")
                        .HasColumnType("INT");

                    b.Property<decimal>("WithdrawableEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventify.Models.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Eventify.Models.Entities.EventPhoto", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Event", "Event")
                        .WithMany("EventPhotos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Payment", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Event", "Event")
                        .WithOne("Payment")
                        .HasForeignKey("Eventify.Models.Entities.Payment", "EventId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Owner", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Eventify.Models.Entities.VenuePhoto", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Venue", "Venue")
                        .WithMany("VenuePhotos")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.Navigation("EventPhotos");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("VenuePhotos");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Owner", b =>
                {
                    b.Navigation("Venues");
                });
#pragma warning restore 612, 618
        }
    }
}
