// <auto-generated />
using System;
using Eventify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eventify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128215139_Seed-Data")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eventify.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ArabicAddress")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ArabicFullName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("BIO")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("BackIdPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FrontIdPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalIDNumber")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Features")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("BIT");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INT");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Address = "Cairo Grand Hall, Nasr City",
                            Category = 1,
                            Description = "A conference discussing the future of AI and technology.",
                            EndDateTime = new DateTime(2025, 4, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Tech Innovations Conference 2025",
                            Features = "Speakers, Workshops, Networking",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 4, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TicketPrice = 500m,
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            Address = "Dubai Outdoor Arena, Marina Walk",
                            Category = 8,
                            Description = "Intense fitness session with professional trainers.",
                            EndDateTime = new DateTime(2025, 5, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Outdoor Fitness Bootcamp",
                            Features = "Trainers, Fresh Air, Group Activities",
                            IsPrivate = false,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 5, 3, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TicketPrice = 150m,
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 3,
                            Address = "Riyadh Event Center",
                            Category = 5,
                            Description = "Connect with entrepreneurs and business owners.",
                            EndDateTime = new DateTime(2025, 6, 18, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Riyadh Business Networking Night",
                            Features = "Networking, Snacks, Business Talks",
                            IsPrivate = false,
                            OrganizerId = 6,
                            StartDateTime = new DateTime(2025, 6, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            TicketPrice = 300m,
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 4,
                            Address = "Corniche Road",
                            Category = 10,
                            Description = "Live music performances by local bands.",
                            EndDateTime = new DateTime(2025, 7, 10, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Alexandria Summer Music Festival",
                            Features = "Live Bands, Food Trucks, Sea View",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 7, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 200m,
                            VenueId = 4
                        },
                        new
                        {
                            EventId = 5,
                            Address = "Pyramids Road",
                            Category = 3,
                            Description = "A meetup focusing on ancient Egyptian culture.",
                            EndDateTime = new DateTime(2025, 3, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Giza Cultural Meetup",
                            Features = "Guided Tour, Cultural Talks",
                            IsPrivate = true,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 3, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TicketPrice = 250m,
                            VenueId = 5
                        },
                        new
                        {
                            EventId = 6,
                            Address = "Khalifa Street",
                            Category = 6,
                            Description = "A premium exhibition showcasing luxury brands.",
                            EndDateTime = new DateTime(2025, 9, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Abu Dhabi Luxury Expo",
                            Features = "Exhibitions, VIP Lounge",
                            IsPrivate = false,
                            OrganizerId = 6,
                            StartDateTime = new DateTime(2025, 9, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 800m,
                            VenueId = 6
                        },
                        new
                        {
                            EventId = 7,
                            Address = "Jeddah North Corniche",
                            Category = 9,
                            Description = "A charity sports event to support children’s hospitals.",
                            EndDateTime = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Jeddah Beach Charity Run",
                            Features = "Medals, Refreshments",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 2, 20, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 100m,
                            VenueId = 7
                        },
                        new
                        {
                            EventId = 8,
                            Address = "Doha Convention Hall",
                            Category = 2,
                            Description = "Hands-on workshop for beginners in software development.",
                            EndDateTime = new DateTime(2025, 8, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Doha Tech Workshop",
                            Features = "Coding Session, Mentors",
                            IsPrivate = false,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 350m,
                            VenueId = 8
                        },
                        new
                        {
                            EventId = 9,
                            Address = "Luxor Temple Road",
                            Category = 4,
                            Description = "A seminar discussing ancient Egyptian heritage.",
                            EndDateTime = new DateTime(2025, 11, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Luxor Historical Seminar",
                            Features = "Speakers, Guided Discussion",
                            IsPrivate = false,
                            OrganizerId = 6,
                            StartDateTime = new DateTime(2025, 11, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TicketPrice = 180m,
                            VenueId = 9
                        },
                        new
                        {
                            EventId = 10,
                            Address = "Sharjah Art Gallery",
                            Category = 10,
                            Description = "A digital art exhibition featuring creatives from the region.",
                            EndDateTime = new DateTime(2025, 10, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Sharjah Digital Art Expo",
                            Features = "Digital Art Panels, Artist Meetups",
                            IsPrivate = false,
                            OrganizerId = 4,
                            StartDateTime = new DateTime(2025, 10, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 5,
                            TicketPrice = 220m,
                            VenueId = 10
                        },
                        new
                        {
                            EventId = 11,
                            Address = "Pyramids Road",
                            Category = 3,
                            Description = "A meetup focusing on ancient Egyptian culture.",
                            EndDateTime = new DateTime(2025, 3, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTitle = "Giza Cultural Meetup",
                            Features = "Guided Tour, Cultural Talks",
                            IsPrivate = false,
                            OrganizerId = 5,
                            StartDateTime = new DateTime(2025, 3, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TicketPrice = 250m,
                            VenueId = 5
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.EventPhoto", b =>
                {
                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("EventId")
                        .HasColumnType("INT");

                    b.HasKey("PhotoUrl", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventPhotos", (string)null);

                    b.HasData(
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 10
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_1.jpg",
                            EventId = 11
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_2.jpg",
                            EventId = 11
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_3.jpg",
                            EventId = 11
                        },
                        new
                        {
                            PhotoUrl = "~/images/event1_4.jpg",
                            EventId = 11
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<int?>("EventId")
                        .HasColumnType("INT");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasFilter("[EventId] IS NOT NULL");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Amount = 200m,
                            EventId = 4,
                            EventName = "Alexandria Summer Music Festival",
                            PaymentDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT4-001",
                            status = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 800m,
                            EventId = 6,
                            EventName = "Abu Dhabi Luxury Expo",
                            PaymentDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT6-001",
                            status = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100m,
                            EventId = 7,
                            EventName = "Jeddah Beach Charity Run",
                            PaymentDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT7-001",
                            status = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 350m,
                            EventId = 8,
                            EventName = "Doha Tech Workshop",
                            PaymentDate = new DateTime(2025, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT8-001",
                            status = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 220m,
                            EventId = 10,
                            EventName = "Sharjah Digital Art Expo",
                            PaymentDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reference = "PAY-EVT10-001",
                            status = 2
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("AirConditioningAvailable")
                        .HasColumnType("BIT");

                    b.Property<bool>("AudioVisualEquipment")
                        .HasColumnType("BIT");

                    b.Property<bool>("BarServiceAvailable")
                        .HasColumnType("BIT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INT");

                    b.Property<bool>("CateringAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(Max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INT");

                    b.Property<bool>("ParkingAvailable")
                        .HasColumnType("BIT");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("ProofOfOwnership")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("RestroomsAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("SpecialFeatures")
                        .IsRequired()
                        .HasColumnType("VARCHAR(Max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("VenueType")
                        .HasColumnType("int");

                    b.Property<bool>("WifiAvailable")
                        .HasColumnType("BIT");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Venues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nasr City",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = false,
                            Capacity = 500,
                            CateringAvailable = true,
                            City = "Cairo",
                            Description = "Large premium indoor venue.",
                            Name = "Cairo Grand Hall",
                            OwnerId = 1,
                            ParkingAvailable = true,
                            PricePerHour = 2500m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Stage, LED Screens",
                            State = "Cairo",
                            VenueType = 1,
                            WifiAvailable = true,
                            ZIP = "11371"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Marina Walk",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = true,
                            Capacity = 300,
                            CateringAvailable = true,
                            City = "Dubai",
                            Description = "Open-air event arena with sea view.",
                            Name = "Dubai Outdoor Arena",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 1800m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Sea View",
                            State = "Dubai",
                            VenueType = 2,
                            WifiAvailable = true,
                            ZIP = "00000"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Olaya Street",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = false,
                            Capacity = 700,
                            CateringAvailable = false,
                            City = "Riyadh",
                            Description = "Modern multi-purpose venue.",
                            Name = "Riyadh Event Center",
                            OwnerId = 3,
                            ParkingAvailable = true,
                            PricePerHour = 3000m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "VIP Rooms",
                            State = "Riyadh",
                            VenueType = 1,
                            WifiAvailable = true,
                            ZIP = "11564"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Corniche Road",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 250,
                            CateringAvailable = true,
                            City = "Alexandria",
                            Description = "Outdoor venue with stunning sea view.",
                            Name = "Alexandria Seaside Hall",
                            OwnerId = 1,
                            ParkingAvailable = false,
                            PricePerHour = 1500m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Sea Breeze, Open Stage",
                            State = "Alexandria",
                            VenueType = 2,
                            WifiAvailable = true,
                            ZIP = "21500"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Pyramids Road",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 600,
                            CateringAvailable = true,
                            City = "Giza",
                            Description = "Cultural event venue facing pyramids.",
                            Name = "Giza Pyramid Arena",
                            OwnerId = 1,
                            ParkingAvailable = true,
                            PricePerHour = 3500m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Historic View",
                            State = "Giza",
                            VenueType = 2,
                            WifiAvailable = false,
                            ZIP = "12556"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Khalifa Street",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = true,
                            Capacity = 450,
                            CateringAvailable = true,
                            City = "Abu Dhabi",
                            Description = "Luxury indoor venue for premium events.",
                            Name = "Abu Dhabi Royal Hall",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 4000m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Gold Interior, VIP Lounge",
                            State = "Abu Dhabi",
                            VenueType = 1,
                            WifiAvailable = true,
                            ZIP = "00001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "North Corniche",
                            AirConditioningAvailable = false,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = true,
                            Capacity = 800,
                            CateringAvailable = false,
                            City = "Jeddah",
                            Description = "Outdoor beach concert venue.",
                            Name = "Jeddah Beach Stage",
                            OwnerId = 3,
                            ParkingAvailable = true,
                            PricePerHour = 2800m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Beachfront Stage",
                            State = "Mecca",
                            VenueType = 2,
                            WifiAvailable = true,
                            ZIP = "23415"
                        },
                        new
                        {
                            Id = 8,
                            Address = "West Bay",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = true,
                            BarServiceAvailable = false,
                            Capacity = 1000,
                            CateringAvailable = false,
                            City = "Doha",
                            Description = "Large conference and exhibition hall.",
                            Name = "Doha Convention Hall",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 5000m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Conference Rooms",
                            State = "Doha",
                            VenueType = 1,
                            WifiAvailable = true,
                            ZIP = "00022"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Luxor Temple Road",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 350,
                            CateringAvailable = false,
                            City = "Luxor",
                            Description = "Historic indoor cultural venue.",
                            Name = "Luxor Cultural Theatre",
                            OwnerId = 1,
                            ParkingAvailable = true,
                            PricePerHour = 1700m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Theatre Stage",
                            State = "Luxor",
                            VenueType = 1,
                            WifiAvailable = false,
                            ZIP = "85958"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Art District",
                            AirConditioningAvailable = true,
                            AudioVisualEquipment = false,
                            BarServiceAvailable = false,
                            Capacity = 120,
                            CateringAvailable = false,
                            City = "Sharjah",
                            Description = "Gallery space for exhibitions.",
                            Name = "Sharjah Art Gallery",
                            OwnerId = 2,
                            ParkingAvailable = true,
                            PricePerHour = 900m,
                            ProofOfOwnership = "~/images/ownership1.jpg",
                            RestroomsAvailable = true,
                            SpecialFeatures = "Art Lighting",
                            State = "Sharjah",
                            VenueType = 1,
                            WifiAvailable = true,
                            ZIP = "00033"
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.VenuePhoto", b =>
                {
                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("VenueId")
                        .HasColumnType("INT");

                    b.HasKey("PhotoUrl", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenuePhotos", (string)null);

                    b.HasData(
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 6
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 7
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 8
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 9
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_1.jpg",
                            VenueId = 10
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_2.jpg",
                            VenueId = 10
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_3.jpg",
                            VenueId = 10
                        },
                        new
                        {
                            PhotoUrl = "~/images/venue1_4.jpg",
                            VenueId = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eventify.Models.Entities.Organizer", b =>
                {
                    b.HasBaseType("Eventify.Models.Entities.ApplicationUser");

                    b.Property<int>("ExperienceYear")
                        .HasMaxLength(50)
                        .HasColumnType("INT");

                    b.Property<int>("PastEventCount")
                        .HasMaxLength(50)
                        .HasColumnType("INT");

                    b.Property<string>("Specialization")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasDiscriminator().HasValue("Organizier");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "1f28393b-f52a-4d31-a0a3-0801eda15518",
                            Country = 1,
                            Email = "Organizer1@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER1@TEST.COM",
                            NormalizedUserName = "FARES",
                            PasswordHash = "AQAAAAIAAYagAAAAEBv0HeE9n7HGuWT6CORPM26N2jIGxzfZRgmA+BcfSS12KFqJTzSfTMOt09Srg6ZxaA==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Fares",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "ca0049c9-cdc6-4781-b2cf-c290e2c1f86e",
                            Country = 1,
                            Email = "Organizer2@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER2@TEST.COM",
                            NormalizedUserName = "AHMED",
                            PasswordHash = "AQAAAAIAAYagAAAAEILcLJ6Zuil/RlAwcXdz9VbF0ekyusoNJXFfyz41rqHApzQy/xAw+3nA+KlOJlr6PQ==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Ahmed",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "فارس حسن علي الداجن",
                            BIO = "Event Organizer passionate about designing and managing unforgettable events. With over 5 years in the industry, I specialize in bringing ideas to life, coordinating every detail, and creating seamless experiences for attendees.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "b6784ed2-50d7-4f24-be36-fb6fa7454e90",
                            Country = 1,
                            Email = "Organizer3@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29801150123456",
                            NormalizedEmail = "ORGANIZER3@TEST.COM",
                            NormalizedUserName = "ZIAD",
                            PasswordHash = "AQAAAAIAAYagAAAAEP/X0PBUJ7tnzeqW7jN+kXs2vPl4D/EZGec0TAMpB7ukZv3O3mZkCw56UTWLBRAGNg==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Ziad",
                            ExperienceYear = 5,
                            PastEventCount = 12,
                            Specialization = "Tech Events"
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Owner", b =>
                {
                    b.HasBaseType("Eventify.Models.Entities.ApplicationUser");

                    b.Property<int>("VenueCount")
                        .HasColumnType("INT");

                    b.Property<decimal>("WithdrawableEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL");

                    b.HasDiscriminator().HasValue("Owner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "ac9efdbc-78b5-477c-bbb4-12bb002728a7",
                            Country = 1,
                            Email = "Owner1@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER1@TEST.COM",
                            NormalizedUserName = "MAHMOUD",
                            PasswordHash = "AQAAAAIAAYagAAAAEOdKBfjp2SVAHCiiePOhhTRjtkaeFeoVW5QJ23PvxwIJuB6Rmx41xxh5R9s+gi/WLQ==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Mahmoud",
                            VenueCount = 3,
                            WithdrawableEarnings = 15000.75m
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "e28083bb-f5dd-4b2a-9cd2-53e34b6eea3b",
                            Country = 1,
                            Email = "Owner2@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER2@TEST.COM",
                            NormalizedUserName = "ALI",
                            PasswordHash = "AQAAAAIAAYagAAAAENK6MlVqGiMX2jHGYz7wNSGq+7ucvLKoAqvwZKmDJlbezFKjSguSLoL2iNSFffBbCw==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Ali",
                            VenueCount = 3,
                            WithdrawableEarnings = 15000.75m
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ArabicAddress = "القاهرة - مصر",
                            ArabicFullName = "محمود سمير عبد الله",
                            BIO = "Venue owner with a passion for hosting memorable experiences. With more than 5 years in the industry, I provide versatile spaces tailored for events of all kinds, ensuring clients and guests enjoy smooth and successful gatherings.",
                            BackIdPhoto = "~/image/back1.jpg",
                            ConcurrencyStamp = "3e787f0c-93f4-4307-bd3c-3bf4bfb11206",
                            Country = 1,
                            Email = "Owner3@test.com",
                            EmailConfirmed = true,
                            FrontIdPhoto = "~/image/front1.jpg",
                            Gender = 1,
                            JoinedDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NationalIDNumber = "29701020123455",
                            NormalizedEmail = "OWNER3@TEST.COM",
                            NormalizedUserName = "AMR",
                            PasswordHash = "AQAAAAIAAYagAAAAEOXZOmZLqAUlbhmU39CggMHHc0k+Yavt/k3OlfON4ChYK+fxto1z/qEFuhl733BJlg==",
                            PhoneNumberConfirmed = false,
                            Photo = "~/image/avatar.jpg",
                            SecurityStamp = "F2821D12 - 02EC - 4EB6 - 88A7 - 393BBAAD4D54",
                            TwoFactorEnabled = false,
                            UserName = "Amr",
                            VenueCount = 3,
                            WithdrawableEarnings = 15000.75m
                        });
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventify.Models.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Eventify.Models.Entities.EventPhoto", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Event", "Event")
                        .WithMany("EventPhotos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Payment", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Event", "Event")
                        .WithOne("Payment")
                        .HasForeignKey("Eventify.Models.Entities.Payment", "EventId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Owner", "Owner")
                        .WithMany("Venues")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Eventify.Models.Entities.VenuePhoto", b =>
                {
                    b.HasOne("Eventify.Models.Entities.Venue", "Venue")
                        .WithMany("VenuePhotos")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Eventify.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Event", b =>
                {
                    b.Navigation("EventPhotos");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Eventify.Models.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("VenuePhotos");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Eventify.Models.Entities.Owner", b =>
                {
                    b.Navigation("Venues");
                });
#pragma warning restore 612, 618
        }
    }
}
